#!/bin/bash
echo "deb $WDVN_URL $WDVN_VER main contrib non-free non-free-firmware
# deb-src $WDVN_URL $WDVN_VER main contrib non-free non-free-firmware

deb $WDVN_URL $WDVN_VER-security main contrib non-free non-free-firmware
# deb-src $WDVN_URL $WDVN_VER-security main contrib non-free non-free-firmware

# $WDVN_VER-updates, to get updates before a point release is made;
# see https://www.debian.org/doc/manuals/debian-reference/ch02.en.html#_updates>
# deb $WDVN_URL $WDVN_VER-updates main contrib non-free non-free-firmware
# deb-src $WDVN_URL $WDVN_VER-updates main contrib non-free non-free-firmware
" >"$1/etc/apt/sources.list"