#!/bin/bash
set -e
echo "deb http://downloads.sourceforge.net/project/ubuntuzilla/mozilla/apt all main" >>"/etc/apt/sources.list"
apt-get -y install dirmngr
apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 2667CA5C
